// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import EditorController from "./editor_controller"
application.register("editor", EditorController)

import ImportController from "./import_controller"
application.register("import", ImportController)

import NewProjectController from "./new_project_controller"
application.register("new-project", NewProjectController)

import TryitController from "./tryit_controller"
application.register("tryit", TryitController)
