// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import EditorController from "./editor_controller"
application.register("editor", EditorController)

import TocController from "./toc_controller"
application.register("toc", TocController)

import TryitController from "./tryit_controller"
application.register("tryit", TryitController)
