# Refreshes the list of journals PreTeXt can typeset an article for.
#
# PreTeXt keeps one source of truth for these -- journals/journals.xml in the PreTeXt
# repository -- and its build script reads that file to turn a publication file's
# <journal name="..."/> into the texstyle that styles the LaTeX (see get_journal_info in
# pretext/lib/pretext.py upstream). Transcribing the list here by hand would mean a picker
# that silently falls behind the journals that actually build, so this fetches it instead
# and writes the two fields the picker needs to config/pretext_journals.yml, which
# Publication::Catalog loads.
#
# Run it when bumping @pretextbook/pretext-html: that package pins which PreTeXt the app's
# XSL comes from, and this reads the same pin (assets/upstream.json), so the journals we
# offer stay the journals that PreTeXt knows. Deliberately not wired into `npm run build`
# -- that runs in watch mode all through development, and a picker should not go blank
# because a laptop was offline.
namespace :pretext do
  desc "Refresh config/pretext_journals.yml from PreTeXt's own journals.xml"
  task :journals do
    require "json"
    require "net/http"
    require "nokogiri"
    require "yaml"

    pin_path = Rails.root.join("node_modules/@pretextbook/pretext-html/assets/upstream.json")
    list_path = Rails.root.join("config/pretext_journals.yml")

    abort "#{pin_path} is missing -- run `npm install` first." unless pin_path.exist?

    repository, ref = JSON.parse(pin_path.read).fetch("source").values_at("repository", "ref")
    url = "https://raw.githubusercontent.com/#{repository}/#{ref}/journals/journals.xml"

    puts "Fetching #{url}"
    response = Net::HTTP.get_response(URI(url))
    abort "#{url} returned #{response.code} #{response.message}." unless response.is_a?(Net::HTTPSuccess)

    # Which entries stand for a publisher's whole family rather than one serial. PreTeXt
    # does not record this: its own table of journals is flat, and journals.xml carries a
    # TODO about categorising them, so the split is ours to keep and to maintain here.
    #
    # Everything unlisted is taken to be an individual journal, which all but a handful
    # are. That is the safe way round -- a family mis-filed as a journal is a picker in a
    # slightly odd order, while a journal mis-filed as a family tells an author that
    # choosing it covers a publisher it does not.
    publisher_wide = %w[ ams elsevier springer-nature taylor-francis ]

    journals = Nokogiri::XML(response.body).xpath("/ptx-journals/journal").map do |journal|
      entry = %w[ code name ].index_with { |field| journal.at_xpath(field)&.text.to_s.strip }
      entry.merge("group" => publisher_wide.include?(entry["code"]) ? "publisher" : "journal")
    end.sort_by { |journal| [ journal["group"] == "publisher" ? 0 : 1, journal["name"].downcase ] }

    # Three ways a fetch can "succeed" and still be worthless: a redirect to an HTML error
    # page, a file moved out from under us, and an upstream edit that mangles an entry.
    # Any of them would quietly empty or corrupt a picker that an author then cannot use,
    # so none of them gets written.
    abort "No journals found at #{url} -- has the file moved?" if journals.empty?

    # A code is written straight into a publication file as an attribute value, and a name
    # is shown to an author. Neither is ours to sanitize after the fact.
    journals.each do |journal|
      abort "Unusable journal entry: #{journal.inspect}" unless
        journal["code"].match?(/\A[a-z0-9-]+\z/) && journal["name"].present?
    end

    previous = (YAML.load_file(list_path) if list_path.exist?) || []
    added = journals.map { |j| j["code"] } - previous.map { |j| j["code"] }
    removed = previous.map { |j| j["code"] } - journals.map { |j| j["code"] }

    list_path.write(<<~HEADER + journals.to_yaml)
      # Generated by `bin/rails pretext:journals` -- do not edit by hand.
      #
      # The journals PreTeXt ships a LaTeX style for, read from journals/journals.xml in
      # #{repository}@#{ref}, which is PreTeXt's own source of truth for them. `code` is
      # what a publication file carries as <journal name="..."/>; `name` is what the build
      # settings picker shows; `group` is "publisher" for a style covering a publisher's
      # whole family and "journal" for one serial, which is how the picker breaks the list
      # up. Refreshed #{Date.today}.
    HEADER

    puts "Wrote #{journals.size} journals to #{list_path.relative_path_from(Rails.root)}"
    puts "  added:   #{added.join(', ')}" if added.any?
    puts "  removed: #{removed.join(', ')}" if removed.any?
    puts "  unchanged" if added.empty? && removed.empty?

    # Upstream names a family "<Publisher> journals", so an entry named that way and not
    # listed above is very likely one filed under the wrong heading. Said rather than
    # obeyed: `publisher_wide` is what decides, because a name is a convention and not a
    # contract, and a silent reclassification is the thing this task exists to avoid.
    journals.each do |journal|
      next unless journal["name"].match?(/journals\z/i) && journal["group"] == "journal"

      puts "  note: #{journal['code']} is named like a publisher-wide style but is filed " \
           "as one journal -- add it to publisher_wide in lib/tasks/pretext.rake if it covers a publisher."
    end
  end
end
