/**
 * The pure half of Tools → Import…: where a file goes, how text converts, and
 * how either result is fitted to the division it is headed for.
 *
 * The fitting tests use real `@pretextbook/import` retargeting and dedupe
 * rather than stubs, since what matters is the markup that comes out — an
 * import that nests `<section>` inside `<section>` is exactly the failure this
 * module exists to prevent.
 */
import { describe, expect, it, vi } from "vitest";
import {
  DIVISION_LADDER,
  importProjectFromFiles,
  ladderDepth,
  type ImportedProjectResult,
} from "@pretextbook/import";
import type { ImportEngine } from "@pretextbook/import/react";
import {
  BUILTIN_IMPORT_ENGINE,
  acceptedImportExtensions,
  alternateTextEngine,
  convertImportFile,
  convertImportText,
  convertImportTextWithEngine,
  detectImportFormat,
  extractDocumentBody,
  fitImportForDivision,
  importTargetDepth,
  resolveImportEngines,
  routeImportFile,
  takenImportIds,
} from "../importConvert";

const pandoc: ImportEngine = {
  id: "pandoc",
  label: "Pandoc",
  acceptExtensions: [".docx", ".epub", ".tex", ".md"],
  convertFile: vi.fn(),
};

/**
 * A standalone document the way a converter writes one — declaration, comment,
 * `<pretext>` with attributes, `<docinfo>` — which is what the remote Pandoc
 * engine hands back after running it through `importProjectFromFiles`.
 */
const pandocDocument = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by pandoc -->
<pretext xml:lang="en-US" xmlns:xi="http://www.w3.org/2001/XInclude">
  <docinfo>
    <macros>\\newcommand{\\R}{\\mathbb{R}}</macros>
  </docinfo>
  <article xml:id="report">
    <title>Report</title>
    <section xml:id="findings">
      <title>Findings</title>
      <p>Body text.</p>
    </section>
  </article>
</pretext>
`;

describe("alternateTextEngine", () => {
  it("is the host's second reader of LaTeX and Markdown", () => {
    const engines = [BUILTIN_IMPORT_ENGINE, pandoc];
    expect(alternateTextEngine("latex", engines)).toBe(pandoc);
    expect(alternateTextEngine("markdown", engines)).toBe(pandoc);
  });

  it("is absent for PreTeXt, and when only one engine reads the format", () => {
    expect(
      alternateTextEngine("pretext", [BUILTIN_IMPORT_ENGINE, pandoc]),
    ).toBeUndefined();
    expect(alternateTextEngine("latex", [BUILTIN_IMPORT_ENGINE])).toBeUndefined();
    expect(
      alternateTextEngine("latex", [
        BUILTIN_IMPORT_ENGINE,
        { ...pandoc, acceptExtensions: [".docx"] },
      ]),
    ).toBeUndefined();
  });
});

describe("convertImportTextWithEngine", () => {
  const engineReturning = (pretextSource: string) => {
    const convertFile = vi.fn<(file: File) => Promise<ImportedProjectResult>>(
      async () =>
        ({ pretextSource, project: { assets: [] } }) as unknown as ImportedProjectResult,
    );
    return { ...pandoc, convertFile };
  };

  it("sends LaTeX, cleaned, as a .tex file and keeps what the cleaner did", async () => {
    const engine = engineReturning(pandocDocument);
    const legacy = String.raw`a \hspace{1cm} b {\bf c} $x$.`;

    const converted = await convertImportTextWithEngine(legacy, "latex", engine, {
      clean: true,
    });

    const [sent] = engine.convertFile.mock.calls[0];
    expect(sent.name).toBe("import.tex");
    const text = await sent.text();
    expect(text).toContain("$x$");
    expect(text).not.toBe(legacy);
    expect(converted.pretext).toBe(pandocDocument);
    expect(converted.findings.length).toBeGreaterThan(0);
  });

  it("sends Markdown as a .md file", async () => {
    const engine = engineReturning(pandocDocument);

    await convertImportTextWithEngine("Some *text*.", "markdown", engine, {
      clean: true,
    });

    const [sent] = engine.convertFile.mock.calls[0];
    expect(sent.name).toBe("import.md");
    expect(await sent.text()).toBe("Some *text*.");
  });

  it("sends nothing when there is nothing to convert", async () => {
    const engine = engineReturning(pandocDocument);

    const converted = await convertImportTextWithEngine("  \n", "latex", engine, {
      clean: true,
    });

    expect(engine.convertFile).not.toHaveBeenCalled();
    expect(converted.pretext).toBe("");
  });
});

describe("extractDocumentBody", () => {
  it("cuts everything up to and including the root's opening tag, and from its closing tag on", () => {
    const body = extractDocumentBody(pandocDocument);

    expect(body).toMatch(/^<section xml:id="findings">/);
    expect(body).toMatch(/<\/section>$/);
    expect(body).not.toMatch(/<\?xml|<!--|<pretext|<docinfo|<article|Report/);
  });

  it("unwraps a <pretext> with no root element in it", () => {
    expect(
      extractDocumentBody(
        '<?xml version="1.0"?>\n<pretext><docinfo><macros/></docinfo>\n<p>x</p>\n</pretext>',
      ),
    ).toBe("<p>x</p>");
  });

  it("comes back empty for an empty root", () => {
    expect(extractDocumentBody("<pretext><article/></pretext>")).toBe("");
  });

  it("cuts an engine's whole document down to what goes inside a division", () => {
    const body = extractDocumentBody(`<pretext>
  <docinfo><macros>\\newcommand{\\R}{\\mathbb{R}}</macros></docinfo>
  <article xml:id="notes">
    <title>My Notes</title>
    <p>Intro.</p>
    <section><title>First</title><p>x</p></section>
  </article>
</pretext>`);

    expect(body.startsWith("<p>Intro.</p>")).toBe(true);
    expect(body).toContain("<section><title>First</title>");
    expect(body).not.toMatch(/<pretext|<docinfo|<article|My Notes/);
  });

  it("leaves a fragment alone", () => {
    const fragment = "<p>a</p>\n<section><title>T</title></section>";
    expect(extractDocumentBody(fragment)).toBe(fragment);
  });
});

describe("importTargetDepth", () => {
  it("puts imported divisions one rung below a ladder division", () => {
    expect(importTargetDepth("chapter")).toBe(ladderDepth("section"));
    expect(importTargetDepth("section")).toBe(ladderDepth("subsection"));
    expect(importTargetDepth("subsection")).toBe(ladderDepth("subsubsection"));
  });

  it("runs off the ladder under a subsubsection", () => {
    expect(importTargetDepth("subsubsection")).toBe(DIVISION_LADDER.length);
  });

  it("uses a root's usual child", () => {
    expect(importTargetDepth("article")).toBe(ladderDepth("section"));
    expect(importTargetDepth("book")).toBe(ladderDepth("chapter"));
  });

  // An <introduction> or <exercises> holds no ladder divisions at all, so no
  // level would be right; moving things would only disguise the problem.
  it("leaves divisions alone under an off-ladder division", () => {
    expect(importTargetDepth("introduction")).toBe(-1);
    expect(importTargetDepth("exercises")).toBe(-1);
    expect(importTargetDepth(null)).toBe(-1);
  });
});

describe("fitImportForDivision", () => {
  const nested =
    "<section><title>A</title><p>x</p>" +
    "<subsection><title>B</title><p>y</p></subsection></section>";

  it("moves sections one level below the receiving section", () => {
    const { source, notes } = fitImportForDivision(nested, {
      parentType: "section",
      takenIds: [],
    });

    expect(source).toMatch(/<subsection>\s*<title>A<\/title>/);
    expect(source).toMatch(/<subsubsection>\s*<title>B<\/title>/);
    expect(source).not.toMatch(/<section\b/);
    expect(notes.join(" ")).toContain("<section> became <subsection>");
  });

  it("keeps sections as sections under an article", () => {
    const { source, notes } = fitImportForDivision(nested, {
      parentType: "article",
      takenIds: [],
    });

    expect(source).toMatch(/<section>\s*<title>A<\/title>/);
    expect(notes).toEqual([]);
  });

  it("turns what runs off the ladder into paragraphs, and says so", () => {
    const { source, notes } = fitImportForDivision(nested, {
      parentType: "subsection",
      takenIds: [],
    });

    expect(source).toMatch(/<subsubsection>\s*<title>A<\/title>/);
    expect(source).toMatch(/<paragraphs>\s*<title>B<\/title>/);
    expect(notes.join(" ")).toContain("<paragraphs>");
  });

  it("renames ids the project already uses, references included", () => {
    const { source, notes } = fitImportForDivision(
      '<section xml:id="sec-first"><title>T</title>' +
        '<p>See <xref ref="sec-first"/>.</p></section>',
      { parentType: "article", takenIds: ["sec-first"] },
    );

    const renamed = /xml:id="([^"]+)"/.exec(source)?.[1];
    expect(renamed).toBeTruthy();
    expect(renamed).not.toBe("sec-first");
    expect(source).toContain(`<xref ref="${renamed}"/>`);
    expect(notes.join(" ")).toContain(`sec-first → ${renamed}`);
  });

  // The LaTeX converter wraps paragraphs only when there is more than one, so
  // a one-line paste arrives as bare text — invalid directly inside a division.
  it("wraps loose text in a paragraph", () => {
    const { source } = fitImportForDivision("Let <m>G</m> be a group.", {
      parentType: "section",
      takenIds: [],
    });
    expect(source).toMatch(/^<p>\s*Let <m>G<\/m> be a group\.\s*<\/p>$/);
  });

  // ...and does the same for a division holding one paragraph, the usual
  // shape of a short section.
  it("wraps loose text inside divisions too", () => {
    const { source } = fitImportForDivision(
      "<section><title>Intro</title>Hello <m>x</m>.</section>",
      { parentType: "article", takenIds: [] },
    );
    expect(source).toMatch(
      /<title>Intro<\/title>\s*<p>\s*Hello <m>x<\/m>\.\s*<\/p>\s*<\/section>/,
    );
  });

  // The importer formats before anything wraps a lone paragraph, putting its
  // inline elements on lines of their own; left alone, that survives the <p>.
  it("pulls inline elements the importer split across lines back together", () => {
    const { source } = fitImportForDivision(
      "<pretext>\n  <article>\n    Let\n    <m>\n      G\n    </m>\n" +
        "    be a\n    <em>\n      group\n    </em>\n    .\n  </article>\n</pretext>",
      { parentType: "section", takenIds: [] },
    );
    expect(source).toMatch(/^<p>\s*Let <m>G<\/m> be a <em>group<\/em>\s*\.\s*<\/p>$/);
  });

  it("comes back empty for a document with nothing in it", () => {
    expect(
      fitImportForDivision(
        "<pretext><article><title>T</title></article></pretext>",
        { parentType: "section", takenIds: [] },
      ).source,
    ).toBe("");
  });
});

describe("convertImportText", () => {
  const legacy = String.raw`a \hspace{1cm} b {\bf c} $x$.`;

  it("converts LaTeX, cleaning it first when asked", () => {
    const cleaned = convertImportText(legacy, "latex", { clean: true });
    expect(cleaned.pretext).toContain("<m>x</m>");
    expect(cleaned.findings.length).toBeGreaterThan(0);

    const literal = convertImportText(legacy, "latex", { clean: false });
    expect(literal.findings).toEqual([]);
  });

  it("converts Markdown", () => {
    expect(
      convertImportText("Some *text*.", "markdown", { clean: true }).pretext,
    ).toContain("<em>text</em>");
  });

  it("passes PreTeXt through", () => {
    expect(
      convertImportText("<p>x</p>", "pretext", { clean: true }).pretext,
    ).toBe("<p>x</p>");
  });
});

describe("detectImportFormat", () => {
  // The document detector keys on `\documentclass` and friends, and would call
  // this PreTeXt.
  it("recognises a LaTeX fragment with no document furniture", () => {
    expect(
      detectImportFormat(String.raw`Let $G$ be a \emph{group} and $H \le G$.`),
    ).toBe("latex");
  });

  it("recognises Markdown", () => {
    expect(detectImportFormat("# Title\n\nSome *text*.")).toBe("markdown");
  });

  it("treats markup and plain prose as PreTeXt", () => {
    expect(detectImportFormat("<p>x</p>")).toBe("pretext");
    expect(detectImportFormat("Just some words.")).toBe("pretext");
  });
});

describe("routing files", () => {
  it("reads the local converters' formats as text, whatever the engines accept", () => {
    expect(routeImportFile("Notes.TEX", [pandoc])).toEqual({
      kind: "text",
      format: "latex",
    });
    expect(routeImportFile("notes.md", [pandoc])).toEqual({
      kind: "text",
      format: "markdown",
    });
    expect(routeImportFile("chapter.ptx", [])).toEqual({
      kind: "text",
      format: "pretext",
    });
  });

  it("sends any other file to the first engine that reads it", () => {
    const engines = [BUILTIN_IMPORT_ENGINE, pandoc];
    expect(routeImportFile("report.docx", engines)).toEqual({
      kind: "engine",
      engine: pandoc,
    });
    expect(routeImportFile("thesis.zip", engines)).toEqual({
      kind: "engine",
      engine: BUILTIN_IMPORT_ENGINE,
    });
  });

  it("says so when nothing reads the file", () => {
    expect(routeImportFile("slides.key", resolveImportEngines()).kind).toBe(
      "unsupported",
    );
  });

  it("offers every readable format in the picker, once each", () => {
    const extensions = acceptedImportExtensions([BUILTIN_IMPORT_ENGINE, pandoc]);
    expect(extensions).toEqual(
      expect.arrayContaining([".tex", ".md", ".ptx", ".zip", ".docx", ".epub"]),
    );
    expect(new Set(extensions).size).toBe(extensions.length);
  });

  it("falls back to the built-in converter when the host supplied none", () => {
    expect(resolveImportEngines()).toEqual([BUILTIN_IMPORT_ENGINE]);
    expect(resolveImportEngines([])).toEqual([BUILTIN_IMPORT_ENGINE]);
    expect(resolveImportEngines([pandoc])).toEqual([pandoc]);
  });
});

describe("convertImportFile", () => {
  const engineReturning = (result: unknown): ImportEngine => ({
    id: "stub",
    label: "Stub",
    acceptExtensions: [".docx"],
    convertFile: vi.fn(async () => result as ImportedProjectResult),
  });

  it("returns the engine's document and reports images it cannot carry", async () => {
    const engine = engineReturning({
      pretextSource: "<pretext><article><p>Hi</p></article></pretext>",
      project: { assets: [{ ref: "img-1" }, { ref: "img-2" }] },
    });
    const file = new File(["bytes"], "report.docx");

    const converted = await convertImportFile(file, [engine]);

    expect(engine.convertFile).toHaveBeenCalledWith(file, {});
    expect(converted.pretext).toContain("<p>Hi</p>");
    expect(converted.notes.join(" ")).toContain("2 images");
  });

  it("throws the engine's own explanation when it fails", async () => {
    const engine = engineReturning({
      pretextError: "Pandoc could not read this file.",
      statusMessages: [],
      warnings: [],
    });
    await expect(
      convertImportFile(new File(["x"], "report.docx"), [engine]),
    ).rejects.toThrow("Pandoc could not read this file.");
  });

  // The remote Pandoc engine runs the server's response through the importer
  // exactly like this, and the prologue survives into `pretextSource`.
  it("fits a Pandoc document the way the remote engine returns it", () => {
    const result = importProjectFromFiles({ "source.ptx": pandocDocument }, {});
    if ("pretextError" in result) throw new Error(result.pretextError);
    expect(result.pretextSource).toContain("<?xml");

    const { source } = fitImportForDivision(result.pretextSource, {
      parentType: "section",
      takenIds: [],
    });

    expect(source).toMatch(/^<subsection xml:id="findings">/);
    expect(source).not.toMatch(/<\?xml|<!--|<pretext|<docinfo|<article|Report/);
  });

  it("converts a real upload through the built-in engine", async () => {
    const file = new File(
      [
        String.raw`\documentclass{article}
\title{Notes}
\begin{document}
\section{First}
Hello $x$.
\end{document}`,
      ],
      "notes.tex",
    );
    const { pretext } = await convertImportFile(file, [BUILTIN_IMPORT_ENGINE]);
    const { source } = fitImportForDivision(pretext, {
      parentType: "section",
      takenIds: [],
    });

    expect(source).toMatch(/<subsection\b[^>]*>\s*<title>First<\/title>/);
    expect(source).not.toMatch(/<pretext|<article|<title>Notes/);
  });
});

describe("takenImportIds", () => {
  it("spans the project's records and the ids written inside its sources", () => {
    expect(
      takenImportIds(
        [
          {
            xmlId: "sec-one",
            source: `<section xml:id="sec-one"><theorem xml:id='thm-a'/></section>`,
          },
        ],
        [{ ref: "fig-plot" }, {}],
        [{ ref: "snip-macro" }],
      ),
    ).toEqual(["sec-one", "fig-plot", "snip-macro", "thm-a"]);
  });
});
