/**
 * @vitest-environment jsdom
 *
 * Tools → Import…: text converts from the left pane, other files go to an
 * engine with nothing shown on the left, and either way the result lands on
 * the right fitted to the division, ready to copy.
 */
import { beforeEach, describe, expect, it, vi } from "vitest";
import { fireEvent, render, screen, waitFor, within } from "@testing-library/react";
import type { ImportedProjectResult } from "@pretextbook/import";
import type { ImportEngine } from "@pretextbook/import/react";
import ImportDialog from "../components/ImportDialog";

// Monaco does not run under jsdom; a textarea keeps the value/onChange contract.
vi.mock("@monaco-editor/react", () => ({
  Editor: ({
    value,
    onChange,
  }: {
    value?: string;
    onChange?: (value: string | undefined) => void;
  }) => (
    <textarea value={value ?? ""} onChange={(e) => onChange?.(e.target.value)} />
  ),
}));

// Reads the editor store, which this dialog does not otherwise need.
vi.mock("../components/StoreFeedbackLink", () => ({ default: () => null }));

const writeText = vi.fn<(text: string) => Promise<void>>(async () => {});

beforeEach(() => {
  writeText.mockClear();
  Object.defineProperty(navigator, "clipboard", {
    value: { writeText },
    configurable: true,
  });
});

const sourceBox = () =>
  within(screen.getByTestId("import-source")).getByRole("textbox");
const outputBox = () =>
  within(screen.getByTestId("import-output")).getByRole(
    "textbox",
  ) as HTMLTextAreaElement;
const chooseFile = (file: File) =>
  fireEvent.change(screen.getByTestId("import-file-input"), {
    target: { files: [file] },
  });

const renderDialog = (engines?: ImportEngine[]) => {
  const onClose = vi.fn();
  render(
    <ImportDialog
      engines={engines}
      parentType="section"
      takenIds={[]}
      onClose={onClose}
    />,
  );
  return { onClose };
};

/** An engine that reads `.docx` and answers with `result`. */
const docxEngine = (
  result: Promise<unknown> | unknown,
): ImportEngine & { convertFile: ReturnType<typeof vi.fn> } => ({
  id: "stub",
  label: "Stub",
  acceptExtensions: [".docx"],
  convertFile: vi.fn(() => Promise.resolve(result as ImportedProjectResult)),
});

const wordDocument = {
  pretextSource: `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by pandoc -->
<pretext xml:lang="en-US"><article xml:id="report"><title>Report</title>
<section><title>Findings</title><p>Body text.</p></section>
</article></pretext>`,
  project: { assets: [{ ref: "img-1" }] },
};

describe("ImportDialog", () => {
  it("converts pasted LaTeX, fitted to the division it is for", () => {
    renderDialog();
    fireEvent.change(sourceBox(), {
      target: { value: String.raw`\section{Intro}` + "\nHello $x$." },
    });
    expect(screen.getByLabelText("Source format")).toHaveDisplayValue(
      "Auto-detect (LaTeX)",
    );

    fireEvent.click(screen.getByRole("button", { name: "Convert" }));

    // Inside a <section>, so the pasted \section arrives a level down.
    expect(outputBox().value).toMatch(/<subsection\b/);
    expect(outputBox().value).not.toMatch(/<section\b/);
    expect(outputBox().value).toContain("<m>x</m>");
    expect(screen.getByTestId("import-notes")).toHaveTextContent(
      "<section> became <subsection>",
    );
  });

  it("copies the result as edited, then closes", async () => {
    const { onClose } = renderDialog();
    fireEvent.change(sourceBox(), { target: { value: "Some *text*." } });
    fireEvent.click(screen.getByRole("button", { name: "Convert" }));
    fireEvent.change(outputBox(), { target: { value: "<p>Edited.</p>" } });

    fireEvent.click(screen.getByRole("button", { name: "Copy and Close" }));

    await waitFor(() => expect(onClose).toHaveBeenCalled());
    expect(writeText).toHaveBeenCalledWith("<p>Edited.</p>");
  });

  it("hands a Word file to the engine and shows no source for it", async () => {
    const engine = docxEngine(wordDocument);
    renderDialog([engine]);
    const file = new File(["binary"], "report.docx");

    chooseFile(file);

    expect(engine.convertFile).toHaveBeenCalledWith(file, {});
    expect(screen.getByTestId("import-file-source")).toHaveTextContent(
      "report.docx",
    );
    expect(screen.queryByTestId("import-source")).not.toBeInTheDocument();
    expect(screen.queryByLabelText("Source format")).not.toBeInTheDocument();

    await waitFor(() => expect(outputBox().value).toMatch(/<subsection\b/));
    expect(outputBox().value).toContain("<title>Findings</title>");
    expect(outputBox().value).not.toMatch(/<pretext|<article|Report/);
    expect(screen.getByTestId("import-notes")).toHaveTextContent("1 image");
  });

  it("loads a .tex file into the source pane instead of converting it whole", async () => {
    const engine = { ...docxEngine(wordDocument), acceptExtensions: [".tex"] };
    renderDialog([engine]);
    const text = String.raw`\section{From a file}`;

    chooseFile(new File([text], "notes.tex"));

    await waitFor(() => expect(sourceBox()).toHaveValue(text));
    expect(screen.getByLabelText("Source format")).toHaveValue("latex");
    expect(engine.convertFile).not.toHaveBeenCalled();
  });

  it("refuses a file nothing can read", () => {
    const alert = vi.spyOn(window, "alert").mockImplementation(() => {});
    renderDialog();

    chooseFile(new File(["x"], "slides.key"));

    expect(alert).toHaveBeenCalled();
    expect(screen.getByTestId("import-source")).toBeInTheDocument();
    alert.mockRestore();
  });

  it("reports a conversion that failed", async () => {
    renderDialog([
      docxEngine({
        pretextError: "Pandoc could not read this file.",
        statusMessages: [],
        warnings: [],
      }),
    ]);

    chooseFile(new File(["x"], "report.docx"));

    expect(await screen.findByRole("alert")).toHaveTextContent(
      "Pandoc could not read this file.",
    );
    expect(screen.getByRole("button", { name: "Copy and Close" })).toBeDisabled();
  });

  // A remote engine can take tens of seconds; an author who gives up and
  // pastes text instead must not have it overwritten when the file finishes.
  it("drops a slow conversion the author has moved on from", async () => {
    let finish!: (value: unknown) => void;
    renderDialog([docxEngine(new Promise((resolve) => (finish = resolve)))]);

    chooseFile(new File(["x"], "report.docx"));
    fireEvent.click(screen.getByRole("button", { name: "Paste text instead" }));
    finish(wordDocument);
    await new Promise((resolve) => setTimeout(resolve, 0));

    expect(outputBox().value).toBe("");
    expect(screen.getByTestId("import-source")).toBeInTheDocument();
  });

  it("lets the author call a snippet Markdown, but never PreTeXt", () => {
    renderDialog();
    fireEvent.change(sourceBox(), { target: { value: "Let $x$ be *prime*." } });
    const select = screen.getByLabelText("Source format");
    // Ties go to LaTeX, which is why the override exists.
    expect(select).toHaveDisplayValue("Auto-detect (LaTeX)");
    expect(
      within(select).queryByRole("option", { name: "PreTeXt" }),
    ).not.toBeInTheDocument();

    fireEvent.change(select, { target: { value: "markdown" } });
    fireEvent.click(screen.getByRole("button", { name: "Convert" }));

    expect(outputBox().value).toContain("<em>prime</em>");
  });

  describe("the host's alternative converter", () => {
    const hostEngines = () => {
      const builtin = { id: "builtin", label: "Built-in", convertFile: vi.fn() };
      const pandoc = {
        id: "pandoc",
        label: "Pandoc",
        acceptExtensions: [".docx", ".tex", ".md"],
        convertFile: vi.fn<(file: File) => Promise<ImportedProjectResult>>(
          () => Promise.resolve(wordDocument as unknown as ImportedProjectResult),
        ),
      };
      return { builtin, pandoc };
    };
    const pandocBox = () => screen.queryByLabelText("Convert with Pandoc instead");

    it("converts pasted LaTeX when the author opts in", async () => {
      const { builtin, pandoc } = hostEngines();
      renderDialog([builtin, pandoc]);
      fireEvent.change(sourceBox(), {
        target: { value: String.raw`\section{Intro}` },
      });

      fireEvent.click(pandocBox()!);
      fireEvent.click(screen.getByRole("button", { name: "Convert" }));

      await waitFor(() =>
        expect(outputBox().value).toContain("<title>Findings</title>"),
      );
      expect(pandoc.convertFile.mock.calls[0][0].name).toBe("import.tex");
      expect(builtin.convertFile).not.toHaveBeenCalled();
    });

    it("stays local until asked", () => {
      const { builtin, pandoc } = hostEngines();
      renderDialog([builtin, pandoc]);
      fireEvent.change(sourceBox(), {
        target: { value: "Some **bold** text.\n\n- one\n- two" },
      });

      expect(pandocBox()).not.toBeChecked();
      fireEvent.click(screen.getByRole("button", { name: "Convert" }));

      expect(outputBox().value).toContain("<li>");
      expect(pandoc.convertFile).not.toHaveBeenCalled();
    });

    it("is not offered for text with nothing to convert, or by a host without one", () => {
      const { builtin, pandoc } = hostEngines();
      const { unmount } = render(
        <ImportDialog
          engines={[builtin, pandoc]}
          parentType="section"
          takenIds={[]}
          onClose={() => {}}
        />,
      );
      fireEvent.change(sourceBox(), { target: { value: "Plain words." } });
      expect(pandocBox()).not.toBeInTheDocument();
      unmount();

      renderDialog();
      fireEvent.change(sourceBox(), {
        target: { value: String.raw`\section{Intro}` },
      });
      expect(pandocBox()).not.toBeInTheDocument();
    });
  });
});
