class Build < ApplicationRecord
  belongs_to :target
  # Denormalized: a build's project is always its target's project. Kept so the existing
  # nested /projects/:project_id/builds/... routes -- including full_callback, whose URL
  # is baked into in-flight submissions and therefore cannot move -- keep working.
  belongs_to :project

  has_one_attached :zip
  has_many :build_files, dependent: :destroy

  # `canceled` is terminal but distinct from `failed`: nothing went wrong with the
  # source, the author simply stopped waiting, and a row that says Failed would send them
  # hunting through a log for an error that isn't there.
  #
  # `queued` is not terminal and not in Target::IN_FLIGHT: it means this build was
  # created but deliberately not sent to FullBuildJob yet, because the author was
  # already at their concurrent-build limit (see User#max_concurrent_builds). It waits
  # here -- not counting against the cap it's waiting on -- until promote_next_queued_build!
  # (see #mark!) hands it a slot.
  #
  # The build server can report success and errors at once: since its "keep output if it
  # exists" change, a build whose CLI exited nonzero still has its output/ zipped and
  # still carries an `artifact_url` -- one target of several failed, or the failure came
  # after most of the output was written -- so the author has something they may well
  # want to preview and even publish, plus an error they need to read. That outcome gets
  # its own status words rather than a boolean flag on `success`, which would otherwise
  # need to sit alongside every other status too (a `received_from_server` build can be
  # flagged just as easily as a `success` one, mid-import):
  #
  #   received_from_server_flagged -- like received_from_server, but the server also
  #                                    reported errors. Carries that fact across the gap
  #                                    until FullBuildArtifactJob finishes the import and
  #                                    picks the status below.
  #   success_awaiting_review      -- imported from a flagged build; usable, but nothing
  #                                    serves it until the author says so (see .live_candidates).
  #   success_errors_accepted      -- the author said so. What a public link now serves.
  #
  # Multiplying `success` out this way only works because nothing outside this class
  # checks the status list directly -- see SUCCESSFUL_STATUSES/.successful below, which
  # is the one place "does this build count as succeeded" is allowed to be a list at all.
  enum :status, { pending: 0, in_progress: 1, success: 2, failed: 3, sent_to_server: 4,
                  received_from_server: 5, canceled: 6, queued: 7,
                  received_from_server_flagged: 8, success_awaiting_review: 9,
                  success_errors_accepted: 10 },
       default: :pending, validate: true

  # Every status that means "this build produced output someone could be shown" --
  # a clean success, or either half of the flagged/reviewed pair above. `success?`
  # (generated by the enum) means only the first of these; reach for `successful?`
  # instead anywhere that used to mean "this build's outcome is usable."
  SUCCESSFUL_STATUSES = %w[ success success_awaiting_review success_errors_accepted ].freeze
  scope :successful, -> { where(status: SUCCESSFUL_STATUSES) }

  def successful?
    SUCCESSFUL_STATUSES.include?(status)
  end

  default_scope { order(created_at: :desc) }

  # The builds a target may serve to readers -- what Target#current_build is chosen from,
  # and therefore what "Publish" exposes and what a public link resolves to. A clean
  # success qualifies; one the build server flagged does not until the author has
  # accepted it (success_awaiting_review is deliberately excluded), so a rebuild that
  # reports errors can never quietly replace working published output with output
  # nobody has looked at.
  scope :live_candidates, -> { where(status: [ :success, :success_errors_accepted ]) }

  def self.in_flight_count(user)
    where(project_id: user.project_ids, status: statuses.values_at(*Target::IN_FLIGHT)).count
  end

  # Builds requested beyond the user's limit queue instead of being refused; see
  # Build#mark!'s promote_next_queued_build!.
  def self.slot_available?(user)
    in_flight_count(user) < user.max_concurrent_builds
  end

  # pretext-cli logs through click, which colours its level labels, so what arrives in a
  # log is "\e[33mwarning: \e[0m..." rather than "warning: ". Nothing downstream renders
  # terminal colour -- the drawer is a <pre> -- so the codes would show up as literal
  # "[33m" noise in front of exactly the lines an author most needs to read. Matches the
  # CSI sequences click emits (colour, bold, reset) plus OSC strings, which nothing sends
  # today but which would otherwise leave a stray "]0;" behind if the CLI ever did.
  ANSI_ESCAPE = /\e\[[0-9;:?]*[ -\/]*[@-~]|\e\][^\a\e]*(?:\a|\e\\)?/

  before_validation :inherit_project_from_target
  after_create :sync_target
  after_destroy :sync_target

  # Whether this build has not yet reached an outcome, and so whether there is anything
  # left to cancel -- either the build server still owes us an answer, or (queued) we
  # haven't sent it there yet. The list itself lives on Target, which is where it is
  # read from most.
  def unresolved?
    Target::UNRESOLVED.include?(status)
  end

  def in_flight?
    Target::IN_FLIGHT.include?(status)
  end

  # Usable output that nonetheless came out of a build the CLI called a failure, whether
  # or not the author has accepted it yet. A build whose *import* then failed or stalled
  # never reaches either of these statuses -- such a build is simply failed, with nothing
  # to preview.
  def built_with_errors?
    success_awaiting_review? || success_errors_accepted?
  end

  # The author saying "use it anyway". Goes through mark! -- with the status this build
  # already has -- rather than a bare update, because what changes here is exactly what
  # current_build is computed from: the pointers have to be recomputed and the row and
  # drawer re-rendered, which is the whole reason mark! exists.
  def accept_errors!
    mark!(:success_errors_accepted)
  end

  # Hands a pending build to the build server and, because everything after that reaches
  # the dashboard by being pushed to it and a push has no receipt, schedules the one thing
  # that goes back and looks. Called wherever a build actually starts (fresh or promoted
  # out of the queue), so every pending build gets both.
  def start!
    FullBuildJob.perform_later(self)
    BuildRecheckJob.set(wait: BuildRecheckJob::RECHECK_AFTER).perform_later(self)
  end

  # The only way a build's status should ever change.
  #
  # Every transition used to be a bare update_column, which skips callbacks -- fine while
  # nothing needed to react, but it means an after_update_commit hook silently never
  # fires. Funnelling them here gives promotion (and, from PR 2, broadcasting the row and
  # the open drawer) exactly one home, so adding a new transition cannot quietly skip any
  # of them.
  #
  # Still update_columns underneath: these are called from jobs where bumping the
  # record's own updated_at is the only side effect we want.
  # Stripping here rather than in the view or at each write site: mark! is the one funnel
  # every log passes through (callback tail, full log fetched out of band, cancel notice),
  # so the column holds plain text and anything that reads it later -- drawer, mailer,
  # console -- gets it clean without repeating the scrub.
  def mark!(status, **attrs)
    attrs[:log] = attrs[:log].gsub(ANSI_ESCAPE, "") if attrs[:log].is_a?(String)

    update_columns(attrs.merge(status: Build.statuses.fetch(status.to_s),
                               updated_at: Time.current))
    target.sync_from_builds!
    target.broadcast_row
    target.broadcast_drawer
    promote_next_queued_build! unless in_flight?
    self
  end

  private

    def inherit_project_from_target
      self.project ||= target&.project
    end

    def sync_target
      # When the whole target is going away, its pointers go with it.
      return if destroyed_by_association

      target&.sync_from_builds!
    end

    # Fires every time a build stops occupying a slot -- finishing, or being canceled
    # before it ever started -- so the next queued build (oldest first, same author,
    # any of their projects) gets that slot immediately rather than waiting on some
    # other trigger to notice. Guarded by slot_available? because not every call here
    # actually freed anything: a queued build's own cancellation reaches this too, and
    # by then nothing may be free at all.
    def promote_next_queued_build!
      owner = target.project.user
      return unless Build.slot_available?(owner)

      next_up = Build.where(project_id: owner.project_ids, status: :queued).reorder(created_at: :asc).first
      return unless next_up

      next_up.mark!(:pending)
      next_up.start!
    end
end
